import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import image from "../public/img/Background.jpg"
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Black Wolf Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.Title}>Front End Heaven </h1>
    <Image src={image} alt="bagas"/>
     
    </div>
  )
}
